"""subject prompt, material context flag, concept exam fields

Revision ID: 8639de791e77
Revises: 881db327543e
Create Date: 2026-10-09 10:00:46.086768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8639de791e77'
down_revision: Union[str, None] = '881db327543e'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # Postgres enums aren't altered by autogenerate, so the new kind has to
    # be added by hand or inserting it fails at runtime
    op.execute("ALTER TYPE materialkind ADD VALUE IF NOT EXISTS 'EXAM_INFO'")

    op.add_column('concepts', sa.Column('marks_lost', sa.Text(), nullable=True))
    op.add_column('concepts', sa.Column('exam_note', sa.Text(), nullable=True))
    op.add_column('subject_profiles', sa.Column('concept_prompt', sa.Text(), nullable=True))
    op.add_column('subject_profiles', sa.Column('prompt_materials_hash', sa.String(length=64), nullable=True))
    op.add_column('subject_profiles', sa.Column('prompt_updated_at', sa.DateTime(timezone=True), nullable=True))

    # NOT NULL with no server_default fails against existing rows, which
    # autogenerate never accounts for. Add with a default, backfill, then
    # drop the default so the model stays the source of truth.
    op.add_column(
        'course_materials',
        sa.Column('include_in_context', sa.Boolean(), nullable=False,
                  server_default=sa.true()),
    )
    op.alter_column('course_materials', 'include_in_context', server_default=None)

    op.add_column(
        'subject_profiles',
        sa.Column('prompt_is_custom', sa.Boolean(), nullable=False,
                  server_default=sa.false()),
    )
    op.alter_column('subject_profiles', 'prompt_is_custom', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_profiles', 'prompt_is_custom')
    op.drop_column('subject_profiles', 'prompt_updated_at')
    op.drop_column('subject_profiles', 'prompt_materials_hash')
    op.drop_column('subject_profiles', 'concept_prompt')
    op.drop_column('course_materials', 'include_in_context')
    op.drop_column('concepts', 'exam_note')
    op.drop_column('concepts', 'marks_lost')
    # ### end Alembic commands ###
