"""concept worked example

Revision ID: 881db327543e
Revises: dd9deb5520ad
Create Date: 2026-10-08 20:03:56.652979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '881db327543e'
down_revision: Union[str, None] = 'dd9deb5520ad'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('worked_example', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'worked_example')
    # ### end Alembic commands ###
